Django_ORM/taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('tasks.api_urls')),
    path('', include('tasks.urls')),
    
]

Django_ORM/taskmanager/tasks/urls.py
from django.urls import path

from tasks import views


urlpatterns = [
  path('', views.index, name='index'),

  path('signup/', views.signup_view, name='signup'),
  path('signin/', views.signin, name='signin'),
  path('signout/', views.signout, name='signout'),

  path('performers/', views.performers, name='performers'),
  path('performer/<int:performers_id>/', views.performer, name='performer'),
  path('create_user/', views.performers, name='create_user'),

  path('projects/', views.projects, name='projects'),
  path('projects/create/', views.create_project, name='projects_create'),
  path('project/<int:project_id>/', views.project, name='project'),

  path('tasks/', views.tasks, name='tasks'),
  path('tasks/create/', views.create_task, name='tasks_create'),
  path('tasks/<int:task_id>/', views.task, name='task'),
  
  
]

Django_ORM/taskmanager/tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Project(models.Model):
  class Meta:
    verbose_name = 'проект'
    verbose_name_plural = 'проекты'

  name = models.CharField(max_length=100, verbose_name='Название')
  description = models.TextField(verbose_name='Описание')
  created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

  def __str__(self):
    return self.name


class User(AbstractUser):
  class Meta:
    verbose_name = 'пользователь'
    verbose_name_plural = 'пользователи'
   

  firstname = models.CharField(max_length=100, verbose_name='Имя')
  lastname = models.CharField(max_length=100, verbose_name='Фамилия')

  def __str__(self):
    return self.username


class TaskStatus(models.Model):
  class Meta:
    verbose_name = 'статус задачи'
    verbose_name_plural = 'статусы задачи'
  name = models.CharField(max_length=100, verbose_name='Название')
  description = models.TextField(verbose_name='Описание')

  def __str__(self):
    return self.name


class Task(models.Model):
  class Meta:
    verbose_name = 'задача'
    verbose_name_plural = 'задачи'

  title = models.CharField(max_length=100, verbose_name='Название')
  description = models.TextField(verbose_name='Описание')
  status = models.ForeignKey(TaskStatus, on_delete=models.PROTECT, verbose_name='Статус')
  created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создана')
  due_date = models.DateField(verbose_name='Срок выполнения')
  project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проект')
  performers = models.ManyToManyField(User, verbose_name='Исполнители')
  comment = models.TextField(blank=True, verbose_name='Коментарий')

  def __str__(self):
    return f'{self.title} ({self.status})'

    
# class Project(models.Model):
#   name = models.CharField(max_length=100)
#   description = models.TextField()
#   created_at = models.DateTimeField(auto_now_add=True)
  
#   def __str__(self):
#       return self.name

# # class Executor(models.Model):
# #   name = models.CharField(max_length=100)
# #   email = models.EmailField()

# #   def __str__(self):
# #       return self.name

# # class User(models.Model):
# #   username = models.CharField(max_length=100)
# #   email = models.EmailField()
  
# #   def __str__(self):
# #       return self.username
# class User(AbstractUser):
#   firstname = models.CharField(max_length=100)
#   lastname = models.CharField(max_length=100)

#   def __str__(self):
#     return self.username


# class TaskStatus(models.Model):
#   name = models.CharField(max_length=100)
#   description = models.TextField()

#   def __str__(self):
#     return self.name



# class Task(models.Model):
#   title = models.CharField(max_length=100)
#   description = models.TextField()
#   status = models.ForeignKey(TaskStatus, on_delete=models.DO_NOTHING)
#   created_at = models.DateTimeField(auto_now_add=True)
#   due_date = models.DateField()
#   project = models.ForeignKey(Project, on_delete=models.CASCADE)
#   performers = models.ManyToManyField(User)
  
#   def __str__(self):
#       return f'{self.title} ({self.status})'


# Create your models here.

Django_ORM/taskmanager/tasks/forms.py
from django import forms
from .models import Project, Task, User, TaskStatus

from django import forms

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'firstname','lastname','password','email'] 
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'логин'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'firstname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя'}),
            'lastname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилия'}),
            'password': forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'floatingPassword',
        'placeholder': 'Пароль',
        'required': True
        })
            # 'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
        }

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Название проекта'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Описание проекта'}),
        }

# class ExecutorForm(forms.ModelForm):
#     class Meta:
#         model = Executor
#         fields = ['name', 'email']
#         widgets = {
#             'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя исполнителя'}),
#             'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email исполнителя'}),
#         }        


# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['name', 'email']
#         widgets = {
#             'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя исполнителя'}),
#             'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email исполнителя'}),
#         }        



class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'project', 'performers', 'comment']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Заголовок задачи'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Описание задачи'}),
            'project': forms.Select(attrs={'class': 'form-control'}),
            'performers': forms.SelectMultiple(attrs={'class': 'form-control', 'style': 'min-height: 150px;'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Комментарий'})
        }

class TaskCreateForm(forms.ModelForm):
  class Meta:
    model = Task
    fields = ['project', 'title', 'description', 'due_date']
  
    widgets = {
      'project': forms.Select(attrs={
        'class': 'form-select',
        'id': 'floatingProjectSelect',
        'aria-label': 'Выбор проекта для привязки задачи',
        'required': True
      }),
      'title': forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingTitle',
        'placeholder': 'Очень простая задача',
        'required': True
      }),
      'description': forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingDescription',
        'placeholder': 'Нужно сделать несколько пунктов...',
        'required': True
      }),
      'due_date': forms.DateInput(attrs={
        'class': 'form-control',
        'id': 'floatingDueDate',
        'type': 'date',
        'required': True
      }),
    }        




# class TaskForm(forms.ModelForm):
# 	class Meta:
# 		model = Task
# 		fields = ['project', 'title', 'description', 'due_date', 'status', 'comment']  # Все поля, которые можно редактировать
# 		widgets = {
# 			'project': forms.Select(attrs={'class': 'form-select'}),
# 			'title': forms.TextInput(attrs={'class': 'form-control'}),
# 			'description': forms.Textarea(attrs={'class': 'form-control'}),
# 			'due_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
# 			'status': forms.Select(attrs={'class': 'form-select'}),
#       'comment':forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Комментарий '}),
# 		}    




class SignupForm(forms.ModelForm):
  confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
    'class': 'form-control',
    'id': 'floatingPasswordConfirm',
    'placeholder': 'Подтверждение пароля',
    'required': True
  }))

  class Meta:
    model = User
    fields = ['firstname', 'lastname', 'username', 'email', 'password']

    widgets = {
      'firstname': forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingTitle',
        'placeholder': 'Очень простая задача',
        'required': True
      }),
      'lastname': forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingLastname',
        'aria-label': 'Фамилия',
        'placeholder': 'Очень простая задача',
        'required': True
      }),
      'username': forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingUsername',
        'placeholder': 'Логин пользователя',
        'aria-label': 'Логин пользователя',
        'required': True
      }),
      'email': forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'floatingEmail',
        'placeholder': 'Почта',
        'required': True
      }),
      'password': forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'floatingPassword',
        'placeholder': 'Пароль',
        'required': True
      }),
    }

  def clean(self):
    cleaned_data = super().clean()
    password = cleaned_data.get('password')
    confirm_password = cleaned_data.get('confirm_password')
    if password != confirm_password:
      raise forms.ValidationError('Пароли не совпадают!')
    return cleaned_data        

Django_ORM/taskmanager/tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ProjectForm, TaskForm, UserForm, SignupForm, TaskCreateForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from rest_framework import generics
from .serializers import TaskSerializer


from tasks.models import Task
from tasks.models import User
from tasks.models import Project
from tasks.models import TaskStatus

# from tasks.models import TaskCreateForm
# from tasks.models import Executor

class TaskListCreateAPIView(generics.ListCreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

class TaskRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


@login_required
def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('project_list')  # Убедитесь, что ть му вас есаршрут для списка проектов
    else:
        form = ProjectForm()
    return render(request, 'create_project.html', {'form': form})

def create_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('performers')  # Убедитесь, что у вас есть маршрут для списка исполнителей
    else:
        form = UserForm()
    return render(request, 'user/create.html', {'form': form})

# def create_task(request):
#     if request.method == 'POST':
#         form = TaskForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('task_list')  # Убедитесь, что у вас есть маршрут для списка задач
#     else:
#         form = TaskForm()
#     return render(request, 'create_task.html', {'form': form})


def index(request):
  return render(request, 'tasks/index.html')

@login_required
def projects(request):
  projects_list = Project.objects.all()
  return render(request, 'project/list.html', context={'projects': projects_list})


  
@login_required
def performers(request):
  performers_list = User.objects.all()
  return render(request, 'tasks/performers.html', context={'performers': performers_list})


def create_user(request):
  if request.method == 'POST':
    name = request.POST['name']
    description = request.POST['description']
    performers_view = Project.objects.create(name=name, description=description)
    return redirect('performers', performers_view.id)
  return render(request, 'user/create.html')   

@login_required
def performer(request, performers_id):
  performer_view = User.objects.get(pk=performers_id)
  performer = User.objects.filter(id=performers_id)
  return render(request, 'tasks/performers.html', context={'performer': performers_id})

@login_required
def tasks(request):
  tasks_list = Task.objects.all()
  return render(request, 'tasks/task/list.html', context={'tasks': tasks_list})

@login_required
def project(request, project_id):
  project_view = Project.objects.get(pk=project_id)
  tasks_list = Task.objects.filter(project_id=project_id)
  return render(request, 'project/details.html', context={'project': project_view, 'tasks': tasks_list})

def create_project(request):
  if request.method == 'POST':
    name = request.POST['name']
    description = request.POST['description']
    project_view = Project.objects.create(name=name, description=description)
    return redirect('project', project_view.id)
  return render(request, 'project/create.html')  

@login_required
def create_task(request):
  if request.method == "POST":
    form = TaskCreateForm(request.POST)
    if form.is_valid():
      # В случае если не нужно изменять сущность задачи
      task = form.save(commit=False)
      task.status = TaskStatus.objects.get(name="Новая")
      task.save()
      return redirect('tasks')
  else:
    form = TaskCreateForm()
  
  projects_list = Project.objects.all()
  return render(request, 'tasks/task/create.html', context={'form': form, 'projects': projects_list})

@login_required
def task(request, task_id):
  task_view = Task.objects.get(pk=task_id)  # Получаем объект Task по первичному ключу
  if request.method == "POST":
    print(request.POST)
    form = TaskForm(request.POST, instance=task_view)  # Передаём существующий объект в форму
    
    if form.is_valid():
      form.save()
      return redirect('tasks')
    else:
      print(form.errors)
      return redirect('index')
  else:
    form = TaskForm(instance=task_view)  # Предзаполняем форму текущими данными
  return render(request, 'tasks/task/details.html', {'form': form, 'task': task})  

def signup_view(request):
  if request.method == 'POST':
    form = SignupForm(request.POST)
    if form.is_valid():
      user = form.save(commit=False)
      user.set_password(form.cleaned_data['password'])  # Хэшируем пароль
      user.save()
      return redirect('signin')
  else:
    form = SignupForm()
  return render(request, 'auth/signup.html', {'form': form})    


def signin(request):
  if request.method == "POST":
    username = request.POST.get("username")
    password = request.POST.get("password")
    
    # Аутентификация пользователя
    user = authenticate(request, username=username, password=password)
    if user is not None:
      login(request, user)  # Вход пользователя
      return redirect('index')  # Перенаправление после успешного входа
    else:
      # Ошибка входа
      return render(request, 'auth/signin.html', {'error': 'Неверный логин или пароль'})
  return render(request, 'auth/signin.html')  


def signout(request):
  # Выходим из системы
  logout(request)
  # Перенаправляем пользователя на страницу входа
  return redirect('signin')

# Create your views here.

Django_ORM/taskmanager/templates/tasks/task/create.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="mb-5">Создание задачи</h1>
    
    <form action="{% url 'tasks_create' %}" method="post">
        {% csrf_token %}
    
        <div class="form-floating mb-3">
            {{ form.project }}
            <label for="floatingSelect">Проект</label>
        </div>
        <div class="form-floating mb-3">
            {{ form.title }}
            <label for="floatingTitle">Название задачи</label>
        </div>
        <div class="form-floating mb-3">
            {{ form.description }}
            <label for="floatingDescription">Описание задачи</label>
        </div>
        <div class="form-floating mb-3">
            {{ form.due_date }}
            <label for="floatingDueDate">Срок исполнения задачи</label>
        </div>
        <div class="d-flex pt-4">
            <button type="submit" class="btn btn-primary">Создать задачу</button>
        </div>
    </form>
{% endblock %}

Django_ORM/taskmanager/templates/tasks/task/details.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="mb-5">Редактирование задачи: {{ task.title }}</h1>

    <form action="" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            {{ form.project }}
            {{ form.project.label_tag }}
        </div>
        <div class="form-floating mb-3">
            {{ form.title }}
            {{ form.title.label_tag }}
        </div>
        <div class="form-floating mb-3">
            {{ form.description }}
            {{ form.description.label_tag }}
        </div>
        <div class="form-floating mb-3">
            {{ form.due_date }}
            {{ form.due_date.label_tag }}
        </div>
        <div class="form-floating mb-3">
            {{ form.status }}
            {{ form.status.label_tag }}
        </div>

        <div class="form-floating mb-3">
            {{ form.performers }}
            {{ form.performers.label_tag }}
        </div>

        <div class="form-floating mb-3">
            {{ form.comment }}
            {{ form.comment.label_tag }}
        </div>
        {% comment %} <label for="id_comment">Комментарий:</label>
            
            {% if form.comment.errors %}
                <div class="text-danger">
                    {{ form.comment.errors }}
                </div>
            {% endif %} {% endcomment %}
        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
        <a href="{% url 'tasks' %}" class="btn btn-secondary">Отмена</a>
    {% comment %} </form>

    <input type="submit" name="_save" class="default" value="{% trans 'Save' %}"/> {% endcomment %}
    
    {% comment %} </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="#" class="btn btn-secondary"> </a>

    <input type="submit" name="_save" class="default" value="{% trans 'Save' %}"/>
            </p>
    </form> {% endcomment %}
{% endblock %}

Django_ORM/taskmanager/templates/tasks/task/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Список задач</h1>
  <p class="mb-5 text-body-secondary">Все задачи в системе</p>
  <div class="row flex-column gap-4 align-items-center">
    {% for task in tasks %}
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <div class="d-flex align-items-center gap-2">
              <h5 class="card-title">{{ task.title }}</h5>
              <span class="badge text-bg-dark mb-1">{{ task.project.name }}</span>
            </div>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ task.status }} - {{ task.due_date }}</h6>
            <pre class="card-text">{{ task.description }}</pre>
            <a href="{% url 'task' task.id %}" class="card-link">Посмотреть задачу</a>
          </div>
        </div>
      </div>
    {% empty %}
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Еще нет задач</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">Смотрю вы любите отдыхать...</h6>
            <p class="card-text">Всем известно, что слона проще есть по частям</p>
            <a href="{% url 'tasks_create' %}" class="card-link">Создать задачу</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}